name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'libyaml-dev libwebsockets-dev libtinyxml2-dev python-yaml libgflags-dev binutils-dev libignition-cmake2-dev libignition-common3-dev libignition-fuel-tools4-dev libignition-gui3-dev libignition-math6-dev libignition-math6-eigen3-dev libignition-msgs5-dev libignition-plugin-dev libignition-tools-dev libignition-rendering3-dev libignition-transport8-dev libsdformat9-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
